### ISSUE TITLE
camera higher than light

### ISSUE THREAD

**Issue by DonJokerov** [Reguluz/Moonflow-Lensflare-System#3]
Hi if i put the camera higher than the light source nothing is rendered.
Not sure if this is the intended behaviour?

**Comment by Reguluz** [comment]
Sorry, I don't understand. Could you describe with more details?

**Comment by DonJokerov** [comment]
Yeah that was really imprecise.
I did some more testing to isolate the issue, here what i found:

In the top picture it is working fine. The "star" is where the light source is (offset 1), the green halo is with offset -0.3.
In the middle picture i moved the camera up, the flare disappears.
In the bottom picture everything is at the same position as in the middle picture. I switched the box collider from the plane off. The flare works again.

It seams a collider in the background does switch off the flare. Some culling issue?

![image](https://user-images.githubusercontent.com/11797287/99185107-03370c80-2748-11eb-845c-eccd0cb2792f.png)

**Comment by Reguluz** [comment]
I still can not understand it clearly, but I think there are some important tips.
If a light source is not on the directional light mode, the flare will disappeared when the gameobject which has the light source component is covered by some other gameobjects on the camera view. It's the function of this plugin, for the purpose to hiding flares of temporarily invisible point lights.
And it based on Raycast system, for it need to use collider to check out if one light source is covered or not.

**Comment by DonJokerov** [comment]
![unityFlare2](https://user-images.githubusercontent.com/11797287/99189138-0938e780-2760-11eb-9494-1119e92bbc22.png)

Well the flare is not in directional mode. The collider is not between the camera and the light, its behind. So the light / flare is not covered...

**Comment by DonJokerov** [comment]
![unityFlare3](https://user-images.githubusercontent.com/11797287/99189532-e576a100-2761-11eb-89b2-0448e53387ba.png)

if i add a cube with collider **behind** the light in your test scene, the flare isn't visible.
If i switch off the collider it is shown.

**Comment by Reguluz** [comment]
So puzzled.....I'll try it later

**Comment by Reguluz** [comment]
> ![unityFlare3](https://user-images.githubusercontent.com/11797287/99189532-e576a100-2761-11eb-89b2-0448e53387ba.png)
> 
> if i add a cube with collider **behind** the light in your test scene, the flare isn't visible.
> If i switch off the collider it is shown.

My fault. I've use the wrong logic of checking covered gameobject. I'd already updated the script. Check out if the question is still happened or not. Thx.

**Comment by DonJokerov** [comment]
Works perfect now. Thanks a lot for fixing it!
