### ISSUE TITLE
When I try to implement this or just try to run the example scene, I don't see any flares

### ISSUE THREAD

**Issue by dsteficar** [Reguluz/Moonflow-Lensflare-System#4]

**Comment by Reguluz** [comment]
It's so weird.....
Though I found something wrong with directional light mode, the sample scene should still have one point light on and runs well.
I have fix the bug of directional light mode, update and see whether all the questions are fixed or not.
I can't really find the reason of your situation..

**Comment by Reguluz** [comment]
If no other question I'll close it.
