### ISSUE TITLE
URPLensFlare.CheckIn() ？

### ISSUE THREAD

**Issue by evapocket** [Reguluz/Moonflow-Lensflare-System#5]
(Vector3.Dot(lightSource[lightIndex].transform.position - _camera.transform.position, _camera.transform.forward) < 0.25f)
if light is directional ,maybe use lightSource[lightIndex].transform.forward to judge  is better.
(lightSource[lightIndex].directionalLight && Vector3.Dot(-lightSource[lightIndex].transform.forward, _camera.transform.forward) < 0f)   this ?

**Comment by Reguluz** [comment]
Directional mode is considered in GetSourceCoordinate(). It's "sourceCoordinate" property is calculated differently with point light and "(Vector3.Dot(lightSource[lightIndex].transform.position - _camera.transform.position, _camera.transform.forward) < 0.25f)" is actually just used for point light
