### ISSUE TITLE
It may have some memory leaks?

### ISSUE THREAD

**Issue by Vampire-Z-V** [Reguluz/Moonflow-Lensflare-System#7]
When I run the sample scene, I see the meshes memory in profiler increase sustainedly.  
![image](https://user-images.githubusercontent.com/19165734/123174890-70b3d400-d4b3-11eb-8890-16924380214f.png)

Then, I change the code in `URPLensFlare.cs`.  
![image](https://user-images.githubusercontent.com/19165734/123175413-53cbd080-d4b4-11eb-906d-06bff8aa75be.png)

It seems every things work fine.
![image](https://user-images.githubusercontent.com/19165734/123175692-c937a100-d4b4-11eb-8434-45b0d58b582e.png)

So, is it the right way to correct this problem?
And I don't know why the mesh will increase after clear :)
Unity Version: 2019.4.19

**Comment by Reguluz** [comment]
Wow……I hadn't recognized this problem and thank you for finding it. When the time I made this solution I was thought of using clear to reuse the memories which has already been declared, but it seemed not taken effect? I think that yours are temporary solution, for I think it will cause some GC on every frame. Maybe there will be a better solution? 
However, I'll soon update the repository with your solution. For it won't make excessive memory overhead

**Comment by Vampire-Z-V** [comment]
Thanks for your reply. I will wait for your solution. ( ੭ ˙ᗜ˙ )੭

**Comment by Reguluz** [comment]
> Thanks for your reply. I will wait for your solution. ( ੭ ˙ᗜ˙ )੭

I'm so sorry for I was busy in the past year and a half, I solved this problem now, and some new features was updated.
