### ISSUE TITLE
Intensive flare shaking at large distances

### ISSUE THREAD

**Issue by CosmicStud** [Reguluz/Moonflow-Lensflare-System#9]
The higher distance past the vector origin the lens flare begins to jitter of course probable due to floating point precision, but what of large scale worlds, just wondering, great asset!

**Comment by Reguluz** [comment]
Sorry I have not find this question for I didn't recognized of this situation. But I think that the flares should not created by a weak light source which is so far from camera, unless it shines so strongly like sun? I wonder if this situation is really needed or not.

**Comment by Reguluz** [comment]
> The higher distance past the vector origin the lens flare begins to jitter of course probable due to floating point precision, but what of large scale worlds, just wondering, great asset!

hey bro, I've updated a new version, insert and replaced with many new calculations. If you could have a try to find this problem solved or not
